openapi: "3.0.3"

info:
  title: "Holodule API"
  version: "0.1"
  description: "Holoduleから配信データを取得するためのAPI"

servers:
  - url: "http://localhost:8080"
    description: "Test Env"

components:
  schemas:
    HoloduleResponse:
      type: object
      properties:
        title:
          type: string
          example: "Live Title"
        channel:
          type: string
          example: "Channel Title"
        url:
          type: string
          example: "http://example.com/holodule/holodule"
    ErrorResponse:
      type: object
      properties:
        reason:
          type: string
        message:
          type: string
          example: "Your request is  bad"

paths:
  /holodule:
    get:
     summary: Get Live schedule
     responses:
       '200':
         description: OK
         content:
           application/json:
            schema:
             type: object
             properties:
               message:
                type: string